### ISSUE TITLE
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'css', attribute 'order': The attribute 'order' is not allowed.

### ISSUE THREAD

**Issue by sajalaspl** [quickshiftin/mage2-ordered-assets#9]
I've overridden the default_head_blocks.xml file.

Trying to add:

    <head>
        <css src="css/prakashan/custom.css" order="100"/>
    </head>

Getting error:

1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'css', attribute 'order': The attribute 'order' is not allowed.
Line: 33

Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'css', attribute 'order': The attribute 'order' is not allowed.
Line: 33

#0 /home/sajal/web/magento2prk/vendor/magento/framework/Config/Dom.php(115): Magento\Framework\Config\Dom->_initDom('<layout xmlns:x...')
#1 /home/sajal/web/magento2prk/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Magento\Framework\Config\Dom->__construct('<layout xmlns:x...', Object(Magento\Framework\App\Arguments\ValidationState), Array, NULL, '/home/sajal/web...', '%message%\nLine:...')
#2 /home/sajal/web/magento2prk/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#3 /home/sajal/web/magento2prk/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...', Array)
#4 /home/sajal/web/magento2prk/vendor/magento/framework/Config/DomFactory.php(42): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...', Array)
#5 /home/sajal/web/magento2prk/vendor/magento/framework/View/Model/Layout/Update/Validator.php(141): Magento\Framework\Config\DomFactory->createDom(Array)

**Comment by quickshiftin** [comment]
Hi, thanks for your report! This is because I'd not done anything with the XSD file which defines the schema of the `css` tag.

It looks like in a [recent version](https://github.com/magento/magento2/commit/d3e24edf30644a892861481dfc722b570f6e070d#diff-cafa9a73d5b2fac003da3e1bdc49fa66), they now support an `order` property out of the box.

I'm unsure how that functionality works, but in testing, even with the alleged built-in support, the `order` property seems not to do anything.

Suffice to say this error should not be there on a recent version with this patch. As a further precaution, I've added support to the extension to add an `option` attribute to the schema if it isn't there.

Please try the latest version 1.1.0 and let me know if you continue to experience the issue.
